name: millionmart_cleaned
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+23

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  speech_to_text: ^5.0.0
  flutter_svg: ^0.22.0
  flutter_staggered_grid_view: ^0.4.0
  bubble_bottom_bar: ^1.2.0
  carousel_slider: ^4.0.0
  responsive_builder: ^0.4.1 
  country_code_picker: ^2.0.1
  like_button: ^2.0.1
  sms_autofill: ^2.0.1 
  flutter_rating_bar: ^4.0.0
  photo_view: ^0.12.0
  sqflite: ^2.0.0+4
  shared_preferences: ^2.0.7
  flutter_material_color_picker: ^1.0.5
  cached_network_image: ^3.1.0
  file_picker: ^4.0.0
  pin_input_text_field: 
  image: ^3.0.2
  http: ^0.13.3
  webview_flutter: ^2.0.12
  flutter_colorpicker: 0.4.0
  google_sign_in: ^5.0.7
  flutter_facebook_auth: ^3.5.1
  image_picker: ^0.8.1+3
  barcode_scan2: any
  resize: 0.1.0
  sizer: 2.0.13
  plugin_platform_interface: any
  flutter_html: any
  flutter_phone_direct_caller: any
  otp_autofill: ^1.1.0
  local_auth: ^1.1.6
  device_info: ^2.0.2
  fluttertoast: ^8.0.8
  sign_in_with_apple: ^3.0.0
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
#  lazy_loading_list: ^1.0.1
#  infinite_scroll_pagination: ^3.1.0
  geolocator: ^7.6.0
  geocoding: ^2.0.1
  intl: ^0.17.0
  url_launcher: ^6.0.10
  avatar_glow: ^2.0.1
#  rating_dialog: ^2.0.1
  firebase_messaging: ^10.0.7
  better_player:
  overlay_support: ^1.2.1
  lottie: ^1.1.0
  flutter_local_notifications: ^8.2.0
  cloud_firestore: ^2.5.3
  flutter_social_content_share: ^1.0.1
  internet_connection_checker: ^0.0.1+2
  app_settings: ^4.1.1
  syncfusion_flutter_pdfviewer: ^19.3.45-beta
  flutter_audio_recorder2: ^0.0.2
  just_audio: ^0.9.16
  audio_session: ^0.1.6+1
  path_provider: ^2.0.2
  shimmer: ^2.0.0
  upgrader: ^3.8.0
  uni_links: ^0.5.1
  encrypt: ^5.0.1
  crypto: ^3.0.1
  flutter_inappwebview: ^5.3.2
  flutter_webview_plugin: ^0.4.0
  flutter_phoenix: ^1.0.0
  restart_app: ^1.1.0
  draggable_fab: ^0.1.4
  flutter_sound_lite: ^8.4.2
  uuid: ^3.0.5
  audioplayers: ^0.20.1
  get_storage: ^2.0.3







dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svgs/sharecart.json
    - assets/svgs/voiceCommands.json
    - assets/svgs/search.json
    - assets/icon/comp.png
    - assets/imageNotFound.png
    - assets/callCus.png
    - assets/image/
    - assets/icon/
    - assets/webapp/
    - assets/image/micon.png
    - assets/svgs/
    - assets/image/otp.png
    - assets/image/mmlogo.png
    - assets/image/manager.png
    - assets/icon/icon.png
    - assets/icon/ex.png
    - assets/icon/cod.png
    - assets/icon/master.png
    - assets/icon/visa.png
    - assets/icon/up.png
    - assets/icon/google.png
    - assets/icon/facebook.png
    - assets/icon/twitter.png
    - assets/icon/mmlogo.png
    - assets/image/yesicon.png
    - assets/icon/million-mall-logo.png
    - assets/icon/logo_gif.gif
    - assets/icon/mmgif.gif
    - assets/icon/sound.gif
    - assets/icon/whatsapp.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/font/OpenSans-Light.ttf
          weight: 300 
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/font/OpenSans-ExtraBold.ttf
          weight: 800
    - family: MyFont
      fonts:
        - asset: assets/font/SFUIText-Regular.ttf
        - asset: assets/font/SFUIText-Bold.ttf
          weight: 700   
    - family: HelveticaNeue
      fonts:
        - asset: assets/font/HelveticaNeue.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
