Map<String, dynamic> configFile =
{
  'color': {
    //Primary Colors Set Deep Blue and Orange
    'primaryColor': '0xFF0B3C68',
    'secondaryColor': '0xffF58323',
    //Status Bar and Navigation Bar AppBar Colors
    'statusBarColor': '0xFFAED0F3',
    'systemNavigationBarColor': '0xFFAED0F3',
    //OnBoard Screens Colors
    'btnGradientColor0': '0xffF58323',
    'btnGradientColor1': '0xffFBA35B',
    'onBoardTitleTextColor': '0xFF656565',
    'onBoardBtnTitleTextColor': '0xFFFFFFFF',
    //Login Screen
    'subtitleColor':'0xffF58323',
    'backgroundColor': '0xFFFFFFFF',
  //  Notification Background Color
    'notificationBackground':'0xffF58323',
    'notificationTextColor':'0xFFFFFFFF',


  },
  'constant':{
    //HomeScreen Pagination
    'loadMoreSize':10,
    'maxItemsCart':10,
  },
  'lang':{
    'usEN':{
      'notifications': 'Notifications',
      'password': 'Password',
      'orders': 'Orders',
      'language': 'Language',
      'easy_payment': 'Easy Search \nMethods',
      'we_connect': 'We make search easy for you with \nImage Search, Voice Search, Barcode Search etc.',
      'next': 'Next',
      'get_your': 'Get Your Delivery \nat Home',
      'we_offer': 'We offers best comfort product \nfor you and your family',
      'start_now': 'Start Now',
      'welcome': 'Welcome to Million Mart',
      'the_eCommerce': 'the eCommerce app for all busniness',
      'mobile_number': 'Mobile Number',
      'forgot_password': 'Forgot Password?',
      'login': 'Login',
      'need_help': 'Need Help?',
      'sign_in': 'Sign In With',
      'don\'t_have': 'Don\'t have an account? ',
      'sign_up': ' Sign Up',
      'signin': ' Sign In',
      'user_registration': 'User Registration',
      'user_name': 'Username',
      'email': 'Email',
      'send_otp': 'SEND OTP',
      'show_password': 'Show Password',
      'register': 'Register',
      'by_creating': 'By creating an account, you agree to\nMillion\'s Mart ',
      'term_condition': 'Terms and Conditions',
      'already_customer': 'Already a Customer?',
      'skip': 'Skip',
      'search': 'Search',
      'see_more': 'See More',
      'view_all': 'View All',
      'home': 'Home',
      'cart': 'Cart',
      'seller_pannel': 'Seller pannel',
      'track_order': 'Track Order',
      'account': 'Account',
      'order_details': 'Order Details',
      'report': 'Report',
      'privacy_policy': 'Privacy Policy',
      'sign_out': 'Sign Out',
      'process_to': 'Process to Checkout',
      'share_cart': 'Share Cart',
      'comparison_items': 'Comparison Items',
      'bargain': 'Bargain Requests',
      'return': 'Return and Refunds',
      'account_info': 'Account Information',
      'settings': 'Settings',
      'faq': 'FAQs',
      'help': 'Help',
      'no_order': 'No Order in History',
      'no_item': 'No items',
      'policy': 'Policy',
      'chat': 'Chat',
      'login_activity': 'Login Activity',
      'logout': 'Logout',
      'contact_us': 'Contact Us',
      'call': 'Call',
      'send_feedback': 'Send Feedback',
      'profile': 'Profile',
      'not_logged': 'You are not Logged in',
      'login_here': 'Login Here',
      'item_cancel': 'Item Cancel',
      'item_return': 'Item Return',
      'file_a_report': 'File a report',
      'write_detail': 'Write Detail Reason',
      'before_reporting':
      'Before reporting an item,please review the Million Mart listing policies.',
      'submit_report': 'Submit Report',
      'Cancel': 'Cancel',
      'report_this': 'Report this Item',
      'Bargain': 'Bargain',
      'call_to_order': 'Call to Order',
      'buy_now': 'Buy Now',
      'add_to_cart': 'Add to Cart',
      'ask_question': 'Ask Question?',
      'information': 'You are not logged in.Please login first',
      'guest_order': 'Guest Order',
      'go_to_login': 'Go to Login Screen',
      'continue': 'Continue',
      'phone_number': 'Phone Number',
      'compare': 'Compare',
      'bargain_items': 'Bargain Items',
      'wishlist_empty': 'Wishlist is Empty',
      'receive_cart': 'Receive Cart',
      'original_price': 'Original Price',
      'tax': 'Tax',
      'total_price': 'Total Price',
      'checkout': 'Checkout',
      'delivery': 'Delivery',
      'address': 'Address',
      'payment': 'Payment',
      'have_promo': 'Have a promo code?',
      'promo_code': 'Promo Code',
      'discount': '(Discount)',
      'sub_total': 'Sub Total',
      'price': 'Price',
      'qty': 'Qty',
      'product_name': 'Product Name',
      'order_summary': 'Order Summary',
      'apply': 'Apply',
      'add_address': 'Add New Address',
      'proceed': 'Proceed',
      'shipping_methods': 'Shipping Methods',
      'payment_methods': 'Payment Methods',
      'enter_sender_email': 'Enter sender ID',
      'receive': 'Receive',
      'share_friends': 'Share With Your Friends',
      'enter_receiver_email': 'Enter Receiver Email',
      'share': 'Share',
      'add_shipping_address': 'Add Shipping Address',
      'city': 'City',
      'state': 'State/Province/Region',
      'zip': 'Zip Code',
      'country': 'Country',
      'save_address': 'Save Address',
      'whatsapp': 'WhatsApp',
      'close': 'Close',
      'no_internet': 'Connect your internet, We\'ll redirect...',
      'request_product': 'Request Product',
      'product_link': 'Product Link',
      'your_name': 'Your Name',
      'description': 'Description',
      'select_image': 'Select Image',
      'order_id': 'Order ID',
      'total_amount': 'Total Amount',
      'order_detail': 'Order Detail',
      'id': 'ID',
      'name': 'Name',
      'detail': 'Detail',
      'total': 'Total',
      'action': 'Action',
      'payment_method': 'Payment Method',
      'status': 'Status',
      'search_qr_login': 'Do you want to Search with QR or Login to Web!!',
      'login_web': 'Login to Web',
      'search_product': 'Search Product',
      'not_reviewed':'Not Reviewed Yet',
      'no_questions':'No Questions Asked',
      'select_color':'Select Color',
      'select_variants':'Select Variants',
      'ratings':'Ratings',
      'click_to_choose_clr':'Click to Choose Color',
      'click_to_choose_sze':'Click to Choose Size',
      'questions_&_answers':'Questions & Answers',
      'similar_products':'Similar Products',
      'ratings_&_reviews':'Ratings & Reviews',
      'million_mall':'Million Mall',
      'no_more_products':'No more Products to load',
      'version':'Version',
      'select_varient':'Select Variant',
      'cart_empty':'Your Cart Is Empty',
      'shop_now':'Shop Now',
      'cart_des':'''Looking like you haven't added anything to your cart''',
      'subtitle':"Absolutely Positively Perfect",



    },
    'urPK':{
      'notifications': 'اطلاعات',
      'password': 'پاس ورڈ',
      'orders': 'احکامات',
      'language': 'زبان',
      'easy_payment': 'ادائیگی کا آسان طریقہ',
      'we_connect':
      'ہم آپ کو آپ کے پسندیدہ آن لائن برانڈز سے جوڑتے ہیں لہذا آئیے اسے ملین مار کے ساتھ براؤز کریں',
      'next': 'اگلے',
      'get_your': 'گھر پر اپنی ترسیل حاصل کریں',
      'we_offer':
      'ہم آپ اور آپ کے خاندان کے لیے بہترین آرام دہ مصنوعات پیش کرتے ہیں',
      'start_now': 'اب شروع کریں',
      'welcome': 'ملین مارٹ میں خوش آمدید',
      'the_eCommerce': 'تمام کاروبار کے لیے ای کامرس ایپ',
      'mobile_number': 'موبائل فون کانمبر',
      'forgot_password': 'پاسورڈ بھول گے؟',
      'login': 'لاگ ان کریں',
      'need_help': 'مدد چاہیے؟',
      'sign_in': 'کے ساتھ سائن ان',
      'don\'t_have': 'کیا آپ کا اکاؤنٹ نہیں ہے؟',
      'sign_up': 'سائن اپ',
      'signin': 'سائن ان',
      'user_registration': 'صارف کا رجسٹریشن',
      'user_name': 'صارف نام',
      'email': 'ای میل',
      'send_otp': 'OTP بھیجیں',
      'show_password': 'پاسورڈ دکھاو',
      'register': 'رجسٹر',
      'by_creating': 'ایک اکاؤنٹ بنا کر ، آپ ملین مارٹ سے اتفاق کرتے ہیں',
      'term_condition': 'شرائط و ضوابط',
      'already_customer': 'پہلے سے ہی ایک گاہک؟',
      'skip': 'چھوڑ دو',
      'search': 'تلاش کریں',
      'see_more': 'دیکھیں مزید',
      'view_all': 'سب دیکھیں',
      'home': 'گھر',
      'cart': 'ٹوکری',
      'seller_pannel': 'بیچنے والا پینل',
      'track_order': 'اپنے آرڈر کا پتا لگائیے',
      'account': 'کھاتہ',
      'order_details': 'آرڈر کی تفصیلات',
      'report': 'رپورٹ',
      'privacy_policy': 'رازداری کی پالیسی',
      'sign_out': 'باہر جائیں',
      'process_to': 'چیک آؤٹ کرنے کا عمل',
      'share_cart': 'شیئر کارٹ',
      'comparison_items': 'موازنہ اشیاء',
      'bargain': 'سودے کی درخواستیں',
      'return': 'واپسی اور واپسی',
      'account_info': 'اکاؤنٹ کی معلومات',
      'settings': 'ترتیبات',
      'faq': 'عمومی سوالات',
      'help': 'مدد',
      'no_order': 'تاریخ میں کوئی حکم نہیں',
      'no_item': 'کوئی اشیاء نہیں',
      'policy': 'پالیسی',
      'chat': 'چیٹ',
      'login_activity': 'لاگ ان سرگرمی',
      'logout': 'لاگ آوٹ',
      'contact_us': 'ہم سے رابطہ کریں',
      'call': 'کال کریں',
      'send_feedback': 'رائے بھیجیں',
      'profile': 'پروفائل',
      'not_logged': 'آپ لاگ ان نہیں ہیں',
      'login_here': 'یہاں لاگ ان کریں',
      'item_cancel': 'آئٹم منسوخ کریں',
      'item_return': 'آئٹم ریٹرن',
      'file_a_report': 'رپورٹ درج کریں',
      'write_detail': 'تفصیل کی وجہ لکھیں',
      'before_reporting':
      'کسی شے کی اطلاع دینے سے پہلے ، براہ کرم ملین مارٹ لسٹنگ پالیسیوں کا جائزہ لیں۔',
      'submit_report': 'رپورٹ جمع کروائیں',
      'Cancel': 'منسوخ کریں',
      'report_this': 'اس آئٹم کی اطلاع دیں',
      'Bargain': 'سودا',
      'call_to_order': 'آرڈر کرنے کے لیے کال کریں',
      'buy_now': 'ابھی خریدیں',
      'add_to_cart': 'ٹوکری میں شامل کری',
      'information': 'آپ لاگ ان نہیں ہیں۔ براہ کرم پہلے لاگ ان کریں',
      'guest_order': 'مہمان کا حکم',
      'go_to_login': 'لاگ ان اسکرین پر جائیں',
      'continue': 'جاری رہے',
      'phone_number': 'فون نمبر',
      'compare': 'موازنہ کریں',
      'bargain_items': 'سودے کی اشیاء',
      'wishlist_empty': 'خواہش کی فہرست خالی ہے',
      'receive_cart': 'ٹوکری وصول کریں',
      'original_price': 'اصل قیمت',
      'tax': 'ٹیکس',
      'total_price': 'کل قیمت',
      'checkout': 'اس کو دیکھو',
      'delivery': 'ترسیل',
      'address': 'پتہ',
      'payment': 'ادائیگی',
      'have_promo': 'ایک پرومو کوڈ ہے؟',
      'promo_code': 'پرومو کوڈ',
      'discount': '(چھوٹ)',
      'sub_total': 'ذیلی کل',
      'price': 'قیمت',
      'qty': 'مقدار',
      'product_name': 'پروڈکٹ کا نام',
      'order_summary': 'حکم کا خلاصہ',
      'apply': 'درخواست دیں',
      'add_address': 'نیا پتہ شامل کریں',
      'proceed': 'آگے بڑھو',
      'shipping_methods': 'ترسیل کے طریقے',
      'payment_methods': 'ادائیگی کے طریقے',
      'enter_sender_email': 'بھیجنے والا ای میل درج کریں',
      'receive': 'وصول کریں',
      'share_friends': 'اپنے دوستوں کے ساتھ شیئر کریں',
      'enter_receiver_email': 'وصول کنندہ ای میل درج کریں',
      'share': 'بانٹیں',
      'add_shipping_address': 'شپنگ ایڈریس شامل کریں',
      'city': 'شہر',
      'state': 'ریاست/صوبہ/علاقہ',
      'zip': 'زپ کوڈ',
      'country': 'ملک',
      'save_address': 'ایڈریس محفوظ کریں',
      'whatsapp': 'واٹس ایپ',
      'close': 'بند کریں',
      'no_internet': 'اپنا انٹرنیٹ منسلک کریں ، ہم ری ڈائریکٹ کریں گے ...',
      'request_product': 'مصنوعات کی درخواست کریں',
      'product_link': 'پروڈکٹ لنک',
      'your_name': 'تمھارا نام',
      'description': 'تفصیل',
      'select_image': 'تصویر منتخب کریں',
      'order_id': 'آرڈر کی شناخت',
      'total_amount': 'کل رقم',
      'order_detail': 'آرڈر کی تفصیل',
      'id': 'آئی ڈی',
      'name': 'نام',
      'detail': 'تفصیل',
      'total': 'کل',
      'action': 'عمل',
      'payment_method': 'ادائیگی کا طریقہ',
      'status': 'حالت',
      'search_qr_login':
      'کیا آپ QR کے ساتھ تلاش کرنا چاہتے ہیں یا ویب پر لاگ ان کرنا چاہتے ہیں !!',
      'login_web': 'ویب پر لاگ ان کریں',
      'search_product': 'مصنوعات تلاش کریں',
      'not_reviewed':'ابھی تک جائزہ نہیں لیا گیا',
      'no_questions':'کوئی سوال نہیں پوچھا گیا',
      'select_color':'رنگ منتخب کریں',
      'select_variants':'متغیرات کو منتخب کریں',
      'ratings':'درجہ بندی',
      'click_to_choose_clr':'رنگ منتخب کرنے کے لیے کلک کریں',
      'click_to_choose_sze':'سائز منتخب کرنے کے لیے کلک کریں',
      'questions_&_answers':'سوالات اور جوابات',
      'ask_question':'سوال پوچھو؟',
      'similar_products':'ملتے جلتے مصنوعات',
      'ratings_&_reviews':'درجہ بندی اور جائزے',
      'million_mall':'ملین مال',
      'no_more_products':'لوڈ کرنے کے لیے مزید مصنوعات نہیں ہیں',
      'version':'ورژن',
      'select_varient':'مختلف قسم کا انتخاب کریں',
      'cart_empty':'آپ کی ٹوکری خالی ہے',
      'shop_now':'ابھی خریداری کریں',
      'cart_des':'ایسا لگتا ہے کہ آپ نے اپنی کارٹ میں کچھ شامل نہیں کیا ہے',
      'subtitle':"Absolutely Positively Perfect",


    },
  },
};
